apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-postgres-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-postgres-app-demo
  template:
    metadata:
      name: py-postgres-app
      labels:
        app: py-postgres-app-demo
    spec:
      containers:
      - name: py-postgres-app-demo
        image: "sharon92/sample-hello-world:4.0"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
              name: pg-test-secret           
---
apiVersion: v1
kind: Service
metadata:
  name: py-postgres-service
  labels:
    run: py-postgres-app-demo
spec:
  type: LoadBalancer
  selector:
    app: py-postgres-app-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80